'use client'

import { useState, useMemo } from 'react'
import { ClimateData } from '@/lib/api'
import KPICards from './KPICards'
import FilterBar from './FilterBar'
import ChartSection from './ChartSection'
import DataTable from './DataTable'

interface DashboardProps {
    initialData: ClimateData[]
}

export default function Dashboard({ initialData }: DashboardProps) {
    const [selectedCountry, setSelectedCountry] = useState<string>('')
    const [selectedYear, setSelectedYear] = useState<number | null>(null)

    const countries = useMemo(() => {
        const unique = new Map()
        initialData.forEach(d => {
            if (!unique.has(d.country_code)) {
                unique.set(d.country_code, { country_code: d.country_code, country_name: d.country_name })
            }
        })
        return Array.from(unique.values()).sort((a, b) => a.country_name.localeCompare(b.country_name))
    }, [initialData])

    const years = useMemo(() => {
        return Array.from(new Set(initialData.map(d => d.year))).sort((a, b) => b - a)
    }, [initialData])

    const filteredData = useMemo(() => {
        let data = initialData
        if (selectedCountry) {
            data = data.filter(d => d.country_code === selectedCountry)
        }
        return data
    }, [initialData, selectedCountry])

    return (
        <div className="container mx-auto px-4 py-12 max-w-7xl">
            <header className="mb-12 border-b border-zinc-800 pb-8">
                <h1 className="text-3xl font-bold text-white mb-2 tracking-tight uppercase">
                    글로벌 기후 인사이트
                </h1>
                <p className="text-zinc-500 font-mono text-sm">
          // 주요 환경 지표 추적 // 출처: WORLD BANK + N8N
                </p>
            </header>

            <FilterBar
                countries={countries}
                selectedCountry={selectedCountry}
                onCountryChange={setSelectedCountry}
                years={years}
                selectedYear={selectedYear}
                onYearChange={setSelectedYear}
            />

            <KPICards data={filteredData} />

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-12">
                <ChartSection
                    title="재생 에너지 비중 (%)"
                    data={filteredData}
                    indicatorCode="EG.FEC.RNEW.ZS"
                    color="#fff"
                />
                <ChartSection
                    title="1인당 전력 소비량 (kWh)"
                    data={filteredData}
                    indicatorCode="EG.USE.ELEC.KH.PC"
                    color="#fff"
                />
                <ChartSection
                    title="메탄 배출량 (kt CO2 eq)"
                    data={filteredData}
                    indicatorCode="EN.ATM.METH.KT.CE"
                    color="#fff"
                />
            </div>

            <DataTable data={filteredData} />

            <footer className="mt-20 py-8 border-t border-zinc-800 text-center text-zinc-600 text-xs uppercase font-mono">
                Generated by Antigravity // Climate Dashboard v1.0
            </footer>
        </div>
    )
}
